language: node_js
node_js:
    - 'lts/*'
dist: trusty
sudo: false

cache:
    directories:
        - node_modules

script:
    - npm run lint
    - npm run build

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist/thesis
    on:
        branch: master
